CREATE DATABASE IF NOT EXISTS library_db;
USE library_db;

DROP TABLE IF EXISTS BorrowRecords;
DROP TABLE IF EXISTS Books;
DROP TABLE IF EXISTS Members;
DROP TABLE IF EXISTS Staff;

CREATE TABLE Staff (
 StaffID INT AUTO_INCREMENT PRIMARY KEY,
 Name VARCHAR(100) NOT NULL,
 Role VARCHAR(50) NOT NULL,
 Email VARCHAR(100) NOT NULL UNIQUE,
 PhoneNumber VARCHAR(20) NOT NULL
);

CREATE TABLE Books (
 BookID INT AUTO_INCREMENT PRIMARY KEY,
 Title VARCHAR(150) NOT NULL,
 Author VARCHAR(100) NOT NULL,
 Genre VARCHAR(50) NOT NULL,
 ISBN VARCHAR(20) NOT NULL UNIQUE,
 Availability BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE Members (
 MemberID INT AUTO_INCREMENT PRIMARY KEY,
 Name VARCHAR(100) NOT NULL,
 PhoneNumber VARCHAR(20) NOT NULL,
 Email VARCHAR(100) NOT NULL UNIQUE,
 Address TEXT NOT NULL,
 MembershipType VARCHAR(30) NOT NULL
);

CREATE TABLE BorrowRecords (
 RecordID INT AUTO_INCREMENT PRIMARY KEY,
 BookID INT NOT NULL,
 MemberID INT NOT NULL,
 StaffID INT NOT NULL,
 BorrowDate DATE NOT NULL,
 DueDate DATE NOT NULL,
 ReturnDate DATE,
 FineAmount DECIMAL(6, 2) NOT NULL DEFAULT 0.00,
 FineStatus VARCHAR(10) NOT NULL DEFAULT 'None',
 FOREIGN KEY (BookID) REFERENCES Books(BookID),
 FOREIGN KEY (MemberID) REFERENCES Members(MemberID),
 FOREIGN KEY (StaffID) REFERENCES Staff(StaffID)
);
